### ISSUE TITLE
Why it's not published to npm?

### ISSUE THREAD

**Issue by voronianski** [tungd/react-catalyst#2]

**Comment by tungd** [comment]
Hi, I will find the time to do it this weekend. Thanks.

**Comment by voronianski** [comment]
@tungd I think it makes sense to make LinkedStateMixin completely separate one. I've used your mixin inside my app (also updated a test spec a bit regarding to latest React updates).

**Comment by tungd** [comment]
Thanks, I updated the repo to work with latest React already, just need to write build script to build it with different format first.

**Comment by wesbos** [comment]
This is on NPM now - can you release a new version to NPM (with my latest 2 pull requests) and close this?

**Comment by tungd** [comment]
Well, the library is published to NPM by someone else. I will try to contact him.

**Comment by wesbos** [comment]
Oh shoot! Yes please - I've got it as a dep in one of my projects

**Comment by tungd** [comment]
Hi, new version (0.3.0) is on NPM.

**Comment by wesbos** [comment]
:smile: Thank you!
