### ISSUE TITLE
Conversions or Formats for Form Inputs

### ISSUE THREAD

**Issue by jdhines** [tungd/react-catalyst#6]
I'm using `valueLink` and `linkState` in a form, but I also want to make sure the value of the input is a number before sending it on to the backend. An input sends strings. Is there a way to force an input field to be say an integer?

**Comment by tungd** [comment]
Under the hood, `valueLink` is just:

    var valueLink = {
      value: this.state.message,
      requestChange: this.handleChange
    };

So you can always make `handleChange` returns an integer, like:

    handleChange: function(newValue) {
        this.setState({message: parseInt(newValue, 10)});
    }

This is advanced use-case and I did not support this yet. There are React form libraries that support full-fletched form schema and it will do the conversion for you, for example: https://github.com/insin/newforms

Thanks
